sentiment/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sentiment.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^sentimentsamples/', include('sentimentsamples.urls', namespace="sentimentsamples")),
)

sentimentsamples/urls.py
from django.conf.urls import url

from sentimentsamples import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
]

sentimentsamples/models.py
from django.db import models

# Create your models here.

class Opinion(models.Model):
    # Enum for sentiment classes
    Positive = 1
    Negative = 2
    Neutral = 3
    SENTIMENT_CLASSES = ((Positive, 'Positive'),
                        (Negative, 'Negative'),
                        (Neutral, 'Neutral'),)
    
    # The text of the opinion
    text = models.CharField(max_length=1000)
    
    #The sentiment of the opinion
    sentiment = models.IntegerField(max_length=10, choices=SENTIMENT_CLASSES, default=Neutral)
    
    source_url = models.CharField(max_length=100, default='Unknown')
    
    def __str__(self):
        return self.text

sentimentsamples/views.py
from django.shortcuts import render
from django.template import RequestContext, loader
from django.views import generic

# Create your views here.
from django.http import HttpResponse
from sentimentsamples.models import Opinion

from TwitterCrawler.TwitterCrawler import  *
import sys
#import os
#os.environ["PYTHONPATH"] = ("..\\..\\sentimentanalysis")
#sys.path.append("C:\\Non_valeo\\Research\\PostDoc\\Sentiment Analysis\\Code\\sentimentanalysis")
#sys.path.append("..\\..\\sentimentanalysis")
from datasetbuilder.DatasetBuilder import DatasetBuilder
from languagemodel.LanguageModel import LanguageModel   
from featuresextractor.FeaturesExtractor import FeaturesExtractor
from classifiers.Classifier import Classifier

twitterCrawler = None
polarityStyle = {'Positive' : 'alert alert-success', 'Negative' : 'alert alert-danger', 'Neutral' : 'alert alert-warning'}

# Start the DatasetBuilder
#-------------------------
# Configurations file xml of the dataset builder
import os
print(os.getcwd())
configFileDatasetBuilder = "sentimentanalysis\\configurations\\Configurations_DatasetBuilder.xml"

datasetSerializationFile = "sentimentanalysis\\output_results\\results_tweets.bin"

# Initialize the DatasetBuilder from serialization file
datasetBuilder = DatasetBuilder(configFileDatasetBuilder, [], datasetSerializationFile)

# Start the LanguageModel
#-------------------------
# Configurations file xml of the language model
configFileLanguageModel = "sentimentanalysis\\configurations\\Configurations_LanguageModel-lexicon.xml"

#positiveLangModelTxtLoadFile = ".\\LanguageModel\\Input\\Eshrag-positive.txt"
positiveLangModelTxtLoadFile = "sentimentanalysis\\input_data\\positive.txt"
#negativeLangModelTxtLoadFile = ".\\LanguageModel\\Input\\Eshrag-negative.txt"
negativeLangModelTxtLoadFile = "sentimentanalysis\\input_data\\negative.txt"
stopWordsFileName = "sentimentanalysis\\input_data\\stop_words.txt"
# The serialization file to save the model
languageModelSerializationFile = "sentimentanalysis\\LanguageModel\\Output\\language_model.bin"

# Start the LanguageModel:

# Initialize the LanguageModel
languageModel = LanguageModel(configFileLanguageModel, stopWordsFileName, [], [], [])
languageModel.LoadSentimentLexiconModelFromTxtFile(positiveLangModelTxtLoadFile, 1)
languageModel.LoadSentimentLexiconModelFromTxtFile(negativeLangModelTxtLoadFile, -1)

# Start the FeaturesExtractor:
#-----------------------------
# Configurations file xml of the features extractor
configFileFeaturesExtractor = "sentimentanalysis\\configurations\\Configurations_FeaturesExtractor-Lexicon.xml"
exportFileName = "sentimentanalysis\\\output_results\\features.txt"
 


# Start the Classifier:
#----------------------
# The serialization file to save the features
configFileClassifier = "sentimentanalysis\\configurations\\Configurations_Classifier-lexicon.xml"





def main(request):
    
    # Handle the query
    #--------------------    
    try:
        # Get the query entered by the user
        query = request.GET['searchbox']
        
        # Start the TwitterCrawler
        import os        
        BASE_DIR = os.path.dirname(os.path.dirname(__file__))
        configFileCrawler = os.path.join(BASE_DIR, 'TwitterCrawler','Configurations', 'Configurations.xml')
        twitterCrawler = TwitterCrawler(configFileCrawler, None, None, None)
        results = twitterCrawler.SearchQueryAPI(query, -1, -1)
        print('Crawling finished')
        #showsome(query)
        
        # Update the DB
        for result in results:
            datasetBuilder.trainSet = []
            datasetBuilder.trainSet.append({'label': 'Positive', 'text':result['text']})
            # Initialize the FeaturesExtractor
            testFeaturesExtractor = FeaturesExtractor(configFileFeaturesExtractor, [], [], languageModel, datasetBuilder.trainSet)
            testFeaturesExtractor.ExtractLexiconFeatures()
            classifier = Classifier(configFileClassifier, [],  None, None, testFeaturesExtractor.features, testFeaturesExtractor.labels)
            sentiment_lexicon_predicted = classifier.LexiconPredict(testFeaturesExtractor.features[0])
            print(sentiment_lexicon_predicted)
            #sentiment_lexicon_predicted = 1
            opinion = Opinion(text=result['text'], sentiment=sentiment_lexicon_predicted, source_url='https://twitter.com/search?q='+query)        
            opinion.save()
        
    except Exception as e:
        # No query entered
        query = ""
            
    # Render the response
    #--------------------   
            
    # Load the main page template
    template = loader.get_template('sentimentsamples/main.html')
    
    # Fill the query list
    opinion_list = Opinion.objects.order_by('text')[:1000]
    
    # Render with the query
    context = RequestContext(request, {'query': query, 'opinion_list' : opinion_list})
   
    return HttpResponse(template.render(context))

import json
import urllib.request, urllib.parse

def showsome(searchfor):
  query = urllib.parse.urlencode({'q': searchfor})
  url = 'http://ajax.googleapis.com/ajax/services/search/web?v=1.0&%s' % query
  search_response = urllib.request.urlopen(url)
  search_results = search_response.read().decode("utf8")
  results = json.loads(search_results)
  data = results['responseData']
  print('Total results: %s' % data['cursor']['estimatedResultCount'])
  hits = data['results']
  print('Top %d hits:' % len(hits))
  for h in hits: print(' ', h['url'])
  print('For more results, see %s' % data['cursor']['moreResultsUrl'])

sentimentsamples/templates/sentimentsamples/main.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<meta http-equiv="X-UA-Compatible" content="IE=edge">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<title>Sentiment Samples</title>

		<!-- Bootstrap -->
		{% load staticfiles %}
        <!--link href="static/style/css/bootstrap.min.css" rel="stylesheet"-->
		<link href="{% static 'style/css/bootstrap.min.css' %}" rel="stylesheet">
		
		<!--link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet"-->

		<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
		<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
		<!--[if lt IE 9]>
		  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
		<![endif]-->
	</head>
	<body>
        <br>
         
		<form action="{% url 'sentimentsamples:main' %}" class="form-inline" method="get">             
            <div class="container">
                <div class="row">
                    <div class="col-lg-4 col-lg-offset-4">
                        <input type="text" "form-control" style="text-align: center" name="searchbox" value="{{query}}">			
                        <button type="submit" class="btn btn-lg btn-success">Submit</button>
                        <!--input type="submit" value="Search"-->
                    </div>
                </div>	
            </div>				
		</form>
        <br>
        
        {% for opinion in opinion_list %}
        	{% if opinion.sentiment == 1 %}
        <div class="alert alert-success" role="alert">
            {{opinion.text}} -- {{opinion.sentiment}} -- {{opinion.source_url}}
        </div>
        	{% elif opinion.sentiment == 2 %}
        <div class="alert alert-danger" role="alert">
            {{opinion.text}} -- {{opinion.sentiment}} -- {{opinion.source_url}}
        </div>        	
        	{% elif opinion.sentiment == 3 %}
        <div class="alert alert-warning" role="alert">
            {{opinion.text}} -- {{opinion.sentiment}} -- {{opinion.source_url}}
        </div>       
        	{% endif %} 	
		{% endfor %}
	</body>
</html>

sentimentsamples/templates/sentimentsamples/test.html
UTORIALS POINT
Simply Easy Learning
<div class="container">
 <h1>Hello, world!</h1> 
 <div class="row"> 
 <div class="col-md-6" style="background-color: #dedef8; box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;"> <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. </p> <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. </p> </div> <div class="col-md-6" style="background-color: #dedef8;box-shadow: inset 1px -1px 1px #444, inset -1px 1px 1px #444;"> <p>Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium. </p> <p> Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. </p> </div> </div>
	</body>
</html>